// AUTO-GENERATED by prepare.ts — do not edit by hand.
// This committed stub keeps `remotion studio` working before the first
// `npm run prepare-video`. Running prepare/render overwrites it.
import type { VideoProps } from './types';

export const generatedProps: VideoProps = { orientation: 'desktop', scenes: [] };
