// AUTO-GENERATED by prepare.ts — do not edit by hand.
import type { VideoProps } from './types';

export const generatedProps: VideoProps = {
  "orientation": "desktop",
  "brand": {
    "name": "Seeclub Stäfa",
    "primary": "#009D53",
    "secondary": "#014DA2",
    "logo": "scs/brand/logo.svg"
  },
  "scenes": [
    {
      "id": "0",
      "part": "Intro",
      "title": "Mitgliederbereich – Anmelden & Passwort setzen",
      "images": [],
      "action": "Einblendung Titel Mitgliederbereich – Anmelden & Passwort setzen",
      "narration": "Herzlich willkommen! In diesem kurzen Video zeige ich dir Schritt für Schritt, wie du dich im Mitgliederbereich des Seeclub Stäfa anmeldest – und wie du dir beim ersten Mal ein Passwort setzt. Du brauchst dafür keine Vorkenntnisse. Wir machen das ganz in Ruhe gemeinsam.",
      "audio": "scs/login/desktop/audio/0.mp3",
      "durationInSeconds": 19.912499999999998,
      "padBefore": 0.4
    },
    {
      "id": "A1",
      "part": "Teil A — Den Mitgliederbereich öffnen",
      "images": [
        "scs/login/desktop/img/01-browser-adresszeile.png"
      ],
      "action": "Cursor zeigt auf die Adresszeile oben",
      "narration": "Als Erstes öffnest du deinen Internet-Browser – das ist das Programm, mit dem du im Internet surfst.",
      "platformHint": "Windows: Edge oder Chrome · Mac: Safari · Linux: Firefox oder Chrome",
      "audio": "scs/login/desktop/audio/A1.mp3",
      "durationInSeconds": 7.6375,
      "padBefore": 0.4
    },
    {
      "id": "A2",
      "part": "Teil A — Den Mitgliederbereich öffnen",
      "images": [
        "scs/login/desktop/img/01-browser-adresszeile.png"
      ],
      "action": "Eintippen `seeclub.org`, dann Enter",
      "narration": "Klicke ganz oben in das lange Feld – die Adresszeile. Tippe dort seeclub.org ein und drücke die Eingabe-Taste (Enter).",
      "platformHint": "Adresszeile = das lange Feld ganz oben",
      "audio": "scs/login/desktop/audio/A2.mp3",
      "durationInSeconds": 10.8125,
      "padBefore": 0.4
    },
    {
      "id": "A3",
      "part": "Teil A — Den Mitgliederbereich öffnen",
      "images": [
        "scs/login/desktop/img/02-seeclub-staefa-mitgliederbereich.png"
      ],
      "action": "Mauszeiger fährt auf den Menüpunkt Mitglieder Bereich",
      "narration": "Es gibt auch einen zweiten Weg: Wenn du auf unserer Vereins-Website seeclub-staefa.ch bist, findest du im Menü den Punkt Mitglieder Bereich. Ein Klick darauf bringt dich genau an dieselbe Stelle.",
      "platformHint": "beide Wege führen zum selben Ziel",
      "audio": "scs/login/desktop/audio/A3.mp3",
      "durationInSeconds": 14.5,
      "padBefore": 0.4
    },
    {
      "id": "B1",
      "part": "Teil B — Anmelden (für wiederkehrende Mitglieder)",
      "images": [
        "scs/login/desktop/img/03-login-leer.png"
      ],
      "action": "Anmeldeseite erscheint",
      "narration": "Jetzt siehst du die Anmeldeseite mit dem Vereinslogo und dem Titel Anmelden. Hier gibst du zwei Dinge ein: deine E-Mail-Adresse und dein Passwort.",
      "audio": "scs/login/desktop/audio/B1.mp3",
      "durationInSeconds": 11.299999999999999,
      "padBefore": 0.4
    },
    {
      "id": "B2",
      "part": "Teil B — Anmelden (für wiederkehrende Mitglieder)",
      "images": [
        "scs/login/desktop/img/04-login-ausgefuellt.png"
      ],
      "action": "E-Mail ins erste Feld tippen",
      "narration": "In das obere Feld E-Mail kommt die E-Mail-Adresse, auf der du die Informationen des Vereins bekommst. Verwende bitte genau diese Adresse.",
      "audio": "scs/login/desktop/audio/B2.mp3",
      "durationInSeconds": 10.9,
      "padBefore": 0.4
    },
    {
      "id": "B3",
      "part": "Teil B — Anmelden (für wiederkehrende Mitglieder)",
      "images": [
        "scs/login/desktop/img/04-login-ausgefuellt.png"
      ],
      "action": "Passwort ins zweite Feld tippen (Punkte)",
      "narration": "In das Feld Passwort tippst du dein persönliches Passwort. Es wird aus Sicherheitsgründen als Punkte angezeigt – das ist normal.",
      "audio": "scs/login/desktop/audio/B3.mp3",
      "durationInSeconds": 10.575,
      "padBefore": 0.4
    },
    {
      "id": "B4",
      "part": "Teil B — Anmelden (für wiederkehrende Mitglieder)",
      "images": [
        "scs/login/desktop/img/04-login-ausgefuellt.png"
      ],
      "action": "Klick auf den Button Anmelden",
      "narration": "Zum Schluss klickst du auf den Knopf Anmelden. Schon bist du drin.",
      "audio": "scs/login/desktop/audio/B4.mp3",
      "durationInSeconds": 6.45,
      "padBefore": 0.4
    },
    {
      "id": "B5",
      "part": "Teil B — Anmelden (für wiederkehrende Mitglieder)",
      "images": [
        "scs/login/desktop/img/05-login-button-passwort-setzen.png"
      ],
      "action": "Pfeil auf den Button Passwort setzen",
      "narration": "Wichtig, wenn du dich zum allerersten Mal anmeldest: Dann hast du noch gar kein Passwort. Klicke in diesem Fall auf den Knopf Passwort setzen – und folge dem nächsten Teil dieses Videos.",
      "platformHint": "beim 1. Mal: weiter mit Teil C",
      "audio": "scs/login/desktop/audio/B5.mp3",
      "durationInSeconds": 13.7875,
      "padBefore": 0.4
    },
    {
      "id": "C1",
      "part": "Teil C — Passwort setzen (erstes Mal oder Passwort vergessen)",
      "images": [
        "scs/login/desktop/img/06-pwdreset-email.png"
      ],
      "action": "Seite Passwort setzen, E-Mail eintippen",
      "narration": "Nach dem Klick auf Passwort setzen erscheint diese Seite. Gib hier deine E-Mail-Adresse ein – wieder die, auf der du die Vereinsinformationen bekommst – und klicke auf OK.",
      "audio": "scs/login/desktop/audio/C1.mp3",
      "durationInSeconds": 12.3125,
      "padBefore": 0.4
    },
    {
      "id": "C2",
      "part": "Teil C — Passwort setzen (erstes Mal oder Passwort vergessen)",
      "images": [
        "scs/login/desktop/img/07-pwdreset-bestaetigung.png"
      ],
      "action": "Bestätigungsmeldung wird gezeigt",
      "narration": "Du bekommst sofort eine Bestätigung: Wir haben dir eine E-Mail mit einer Anleitung geschickt. Du musst jetzt nichts weiter tun, ausser dein E-Mail-Programm zu öffnen.",
      "audio": "scs/login/desktop/audio/C2.mp3",
      "durationInSeconds": 12.0375,
      "padBefore": 0.4
    },
    {
      "id": "C3",
      "part": "Teil C — Passwort setzen (erstes Mal oder Passwort vergessen)",
      "images": [
        "scs/login/desktop/img/08-PLATZHALTER-reset-mail.png"
      ],
      "action": "E-Mail mit Link, Pfeil auf den Link",
      "narration": "Öffne die E-Mail von uns. Darin findest du einen Link zum Anklicken. Tippe bzw. klicke einmal darauf. (Falls die E-Mail nicht da ist: schau auch im Spam- oder Werbeordner nach.)",
      "platformHint": "Tipp: auch im Spam-Ordner schauen",
      "audio": "scs/login/desktop/audio/C3.mp3",
      "durationInSeconds": 16.1375,
      "padBefore": 0.4
    },
    {
      "id": "C4",
      "part": "Teil C — Passwort setzen (erstes Mal oder Passwort vergessen)",
      "images": [
        "scs/login/desktop/img/09-confirm-neues-passwort.png"
      ],
      "action": "Seite Neues Passwort festlegen, Passwort eintippen",
      "narration": "Der Link öffnet diese Seite: Neues Passwort festlegen. Denke dir hier ein Passwort aus, das nur du kennst – mindestens 6 Zeichen lang. Tippe es ein und klicke auf Passwort speichern.",
      "platformHint": "mindestens 6 Zeichen",
      "audio": "scs/login/desktop/audio/C4.mp3",
      "durationInSeconds": 14.875,
      "padBefore": 0.4
    },
    {
      "id": "C5",
      "part": "Teil C — Passwort setzen (erstes Mal oder Passwort vergessen)",
      "images": [
        "scs/login/desktop/img/10-confirm-erfolg.png"
      ],
      "action": "Erfolgsmeldung",
      "narration": "Geschafft! Du siehst die Meldung: Passwort erfolgreich geändert. Dein Passwort ist nun gesetzt.",
      "audio": "scs/login/desktop/audio/C5.mp3",
      "durationInSeconds": 9.7,
      "padBefore": 0.4
    },
    {
      "id": "C6",
      "part": "Teil C — Passwort setzen (erstes Mal oder Passwort vergessen)",
      "images": [
        "scs/login/desktop/img/03-login-leer.png",
        "__placeholder__:11-mitgliederbereich-home.png"
      ],
      "action": "Zurück zur Anmeldung, dann eingeloggter Bereich",
      "narration": "Jetzt kannst du dich ganz normal anmelden: E-Mail und dein neues Passwort eingeben, auf Anmelden klicken – und du bist im Mitgliederbereich.",
      "audio": "scs/login/desktop/audio/C6.mp3",
      "durationInSeconds": 10.7,
      "padBefore": 0.4
    },
    {
      "id": "O1",
      "part": "Outro",
      "images": [
        "__placeholder__:11-mitgliederbereich-home.png"
      ],
      "action": "Begrüssung Willkommen im Mitgliederbereich!",
      "narration": "Wunderbar – du bist drin! Merke dir deine E-Mail-Adresse und dein Passwort gut. Beim nächsten Mal genügt das Anmelden in Teil B. Falls du dein Passwort einmal vergisst, gehst du einfach wieder über Passwort setzen. Viel Freude im Mitgliederbereich!",
      "audio": "scs/login/desktop/audio/O1.mp3",
      "durationInSeconds": 20.374999999999996,
      "padBefore": 0.4
    }
  ]
};
