import { copyFileSync, existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { parseScript } from './parse-script';
import { synthesize } from './tts';
import { FPS, type Orientation, type SceneProps, type VideoProps } from './types';

const PAD_BEFORE = 0.4; // ruhiges Tempo: lead-in before narration
const PAD_AFTER = 0.7; //  and a beat after each scene

const PRODUCER_ROOT = resolve(__dirname, '..'); // _producer/
const VIDEOS_ROOT = resolve(PRODUCER_ROOT, '..'); // videos/
const PUBLIC_DIR = join(PRODUCER_ROOT, 'public');

export const PLACEHOLDER = '__placeholder__:';

/** Prefer a real screenshot; fall back to the _reference sample; else null. */
function resolveImage(variantDir: string, file: string): string | null {
  const real = join(variantDir, 'assets', file);
  if (existsSync(real)) return real;
  const ref = join(variantDir, 'assets', '_reference', file);
  if (existsSync(ref)) return ref;
  return null;
}

export type PrepareResult = VideoProps & {
  missing: string[]; // screenshots referenced but not found (placeholders used)
  usedReference: boolean;
  hasAudio: boolean;
};

/**
 * Parse a script, synthesize narration, stage all assets under public/, and
 * write src/generated-props.ts (for `remotion studio`). Returns the input props
 * for renderMedia plus a small report.
 */
export async function prepare(tenantTopic: string, variant: Orientation): Promise<PrepareResult> {
  const [tenant, topic] = tenantTopic.split('/');
  if (!tenant || !topic) {
    throw new Error(`Expected "<tenant>/<topic>", got "${tenantTopic}"`);
  }
  const variantDir = join(VIDEOS_ROOT, tenant, topic, variant);
  const scriptPath = join(variantDir, 'script.md');
  if (!existsSync(scriptPath)) {
    throw new Error(`script.md not found: ${scriptPath}`);
  }

  const voice = process.env.SPEECH_VOICE ?? 'de-CH-LeniNeural';
  const parsed = parseScript(scriptPath);

  const stageRel = `${tenant}/${topic}/${variant}`;
  const stageDir = join(PUBLIC_DIR, stageRel);
  rmSync(stageDir, { recursive: true, force: true });
  mkdirSync(join(stageDir, 'img'), { recursive: true });
  mkdirSync(join(stageDir, 'audio'), { recursive: true });

  const missing: string[] = [];
  let hasAudio = false;
  const scenes: SceneProps[] = [];

  for (const s of parsed) {
    const images: string[] = [];
    for (const file of s.images) {
      const src = resolveImage(variantDir, file);
      if (src) {
        copyFileSync(src, join(stageDir, 'img', file));
        images.push(`${stageRel}/img/${file}`);
      } else {
        missing.push(file);
        images.push(`${PLACEHOLDER}${file}`);
      }
    }

    const outMp3 = join(stageDir, 'audio', `${s.id}.mp3`);
    const tts = s.narration
      ? await synthesize(s.narration, voice, outMp3)
      : { audioPath: null, durationInSeconds: 2.5 };
    if (tts.audioPath) hasAudio = true;

    scenes.push({
      id: s.id,
      part: s.part,
      title: s.title,
      images,
      action: s.action,
      narration: s.narration,
      platformHint: s.platformHint,
      audio: tts.audioPath ? `${stageRel}/audio/${s.id}.mp3` : null,
      durationInSeconds: tts.durationInSeconds + PAD_BEFORE + PAD_AFTER,
      padBefore: PAD_BEFORE,
    });
  }

  const props: VideoProps = { orientation: variant, scenes };

  writeFileSync(
    join(PRODUCER_ROOT, 'src', 'generated-props.ts'),
    `// AUTO-GENERATED by prepare.ts — do not edit by hand.\n` +
      `import type { VideoProps } from './types';\n\n` +
      `export const generatedProps: VideoProps = ${JSON.stringify(props, null, 2)};\n`,
  );

  return {
    ...props,
    missing: [...new Set(missing)],
    usedReference: missing.length === 0 && scenes.some((sc) => sc.images.length > 0),
    hasAudio,
  };
}

export { FPS };
