import { Component, computed, inject } from '@angular/core';
import { IonApp, IonAvatar, IonButtons, IonContent, IonHeader, IonImg, IonItem, IonLabel, IonMenu, IonRouterOutlet, IonSplitPane, IonTitle, IonToolbar } from '@ionic/angular/standalone';

import { AuthInfoComponent } from '@bk2/auth-ui';
import { MenuComponent } from '@bk2/cms-menu-feature';
import { AppStore } from '@bk2/shared-feature';
import { RoleName } from '@bk2/shared-models';
import { ConnectionStatusButtonComponent, SpinnerComponent, AvatarUserComponent } from '@bk2/shared-ui';
import { getImgixUrlWithAutoParams, hasRole } from '@bk2/shared-util-core';

@Component({
  imports: [
    MenuComponent, AuthInfoComponent, SpinnerComponent, ConnectionStatusButtonComponent, AvatarUserComponent,
    IonApp, IonSplitPane, IonMenu, IonHeader, IonContent, IonToolbar, IonRouterOutlet, IonButtons, IonAvatar,
    IonImg, IonLabel, IonItem,
    AvatarUserComponent
],
  selector: 'bk-root',
  standalone: true,
  styles: [
    `
      /* ----------------------------------------------
    * Generated by Animista on 2024-8-1 15:19:28
    * Licensed under FreeBSD License.
    * See http://animista.net/license for more info. 
    * w: http://animista.net, t: @cssanimista
    * ---------------------------------------------- */

      /**
    * ----------------------------------------
    * animation kenburns-top
    * ----------------------------------------
    */
      @-webkit-keyframes kenburns-top {
        0% {
          -webkit-transform: scale(1) translateY(0);
          transform: scale(1) translateY(0);
          -webkit-transform-origin: 50% 16%;
          transform-origin: 50% 16%;
        }
        100% {
          -webkit-transform: scale(1.25) translateY(-15px);
          transform: scale(1.25) translateY(-15px);
          -webkit-transform-origin: top;
          transform-origin: top;
        }
      }
      @keyframes kenburns-top {
        0% {
          -webkit-transform: scale(1) translateY(0);
          transform: scale(1) translateY(0);
          -webkit-transform-origin: 50% 16%;
          transform-origin: 50% 16%;
        }
        100% {
          -webkit-transform: scale(1.25) translateY(-15px);
          transform: scale(1.25) translateY(-15px);
          -webkit-transform-origin: top;
          transform-origin: top;
        }
      }

      .logo-container {
        display: flex;
        align-items: center;
        justify-content: center;
        background-color: #1a5fab;
        height: 100%;
      }
      .kenburns-top {
        -webkit-animation: kenburns-top 1s cubic-bezier(0.6, -0.28, 0.735, 0.045) both;
        animation: kenburns-top 1s cubic-bezier(0.6, -0.28, 0.735, 0.045) both;
        margin: 0 auto;
        display: block;
        width: 33%;
      }
    `,
  ],
  template: `
    @defer {
    <!--
        bk app has one single, left menu -> main-menu
        menuitem contents are dependent on e.g. authentication and user role
        register all menus here, derive them from BaseMenu and set a menu id within the class
        use MenuController with this.menu.enable(true, menuId) to switch the menus
      -->
    <ion-app>
      <ion-split-pane contentId="main">
        <ion-menu side="start" menuId="main" contentId="main" type="overlay">
          <ion-header>
            <ion-toolbar color="secondary">
              <ion-buttons slot="start"><bk-connection-status-button /></ion-buttons>
              <ion-item lines="none" color="secondary">
                <ion-label>{{ appStore.appConfig().appName }}</ion-label>
              </ion-item>
              <ion-buttons slot="end"><bk-avatar-user [currentUser]="appStore.currentUser()" /></ion-buttons>
            </ion-toolbar>
          </ion-header>
          <ion-content>
            @if (isUserSessionReady()) {
              <bk-menu [menuName]="mainMenuName()" />
            } @else {
              <bk-spinner />
            }
            @if(showDebugInfo()) {
              <bk-auth-info [currentUser]="appStore.currentUser()" [fbUser]="appStore.fbUser()" [isAuthenticated]="appStore.isAuthenticated()" [isAdmin]="hasRole('admin')" />
            }
          </ion-content>
        </ion-menu>
        <ion-router-outlet id="main" />
      </ion-split-pane>
    </ion-app>
    } @placeholder (minimum 1000ms) {
    <div class="logo-container">
      <img class="kenburns-top" [src]="logoUrl()" alt="logo" />
    </div>
    } @loading(after 100ms; minimum 500ms) {
    <span>Bitte warten... die Applikation wird geladen.</span>
    } @error {
    <span>Oops ! Die Applikation konnte nicht geladen werden. Bitte nochmals probieren.</span>
    }
  `,
})
export class AppComponent {
  protected appStore = inject(AppStore);

  protected showDebugInfo = computed(() => this.appStore.showDebugInfo());
  protected mainMenuName = computed(() => `main_${this.appStore.tenantId()}`);
  protected logoUrl = computed(() => `${this.appStore.services.imgixBaseUrl()}/${getImgixUrlWithAutoParams(this.appStore.appConfig().logoUrl)}`);

  protected isUserSessionReady = computed(() => {
    const fbUser = this.appStore.fbUser();
    const currentUser = this.appStore.currentUser();

    // If the Firebase auth state is null, the user is logged out. We are ready.
    if (fbUser === null) {
      return true;
    }

    // If the Firebase auth state is populated, we are only ready if the
    // corresponding application user object has also been found.
    if (fbUser && currentUser) {
      return true;
    }

    // Otherwise, we are in a transitional state (e.g., logging in but waiting for data).
    return false;
  });

  protected hasRole(role: RoleName | undefined): boolean {
    return hasRole(role, this.appStore.currentUser());
  }
}
